### PR TITLE
Bumps the Chrono Version and renames UTC

### PR DESCRIPTION
**Pull request by tl8roy**
The bumps the chrono version to 0.4 and renames UTC to Utc

### CODE REVIEW

**Comment by apiraino** [comment]
Hi,

I'm not sure but I think that this patch will fix using rusqlite against `chrono==0.4`?
I've updated chrono to 04 and now get this error:
```
error[E0277]: the trait bound `chrono::DateTime<chrono::Local>: rusqlite::types::ToSql` is not satisfied
  --> src/lib.rs:77:30
   |
77 |                              &pub_date]) {
   |                              ^^^^^^^^^ the trait `rusqlite::types::ToSql` is not implemented for `chrono::DateTime<chrono::Local>`
```
and `pub_date` is a `pub_date: DateTime<Local>`.
I've checked the CHANGELOG for 0.4 but could find anything related.

Is something else needed to ensure compatibility with chrono==0.4?

**Comment by tl8roy** [comment]
Yes, this patch should help with that

**Comment by vityafx** [comment]
How much time do you need to fix the checks @tl8roy ? I guess this is why this PR was not merged.

**Comment by tl8roy** [comment]
@vityafx As the error appears to be ```error: linking with `link.exe` failed: exit code: 1181```, I am not sure what I can fix

**Comment by jgallagher** [comment]
Equivalent changes were merged as part of #302. Thanks!

**Pull request closed without merging**
