### PR TITLE
Fix format string error in rusqlite::trace::log

### PR DESCRIPTION
**Pull request by thomcc**
:/

### CODE REVIEW

**Comment by thomcc** [comment]
No, CString::new NUL-terminates the string as well as checks it for internal NULs.

**Comment by gwenn** [comment]
Sorry ! I see now why we need to pass a dummy format string: in case the message contains `%s` or any other format.

**Comment by thomcc** [comment]
Yes. Also %n is particularly bad since it can be used to write to places on the stack, like the return address of the function!

**Comment by gwenn** [comment]
Thanks for yours explanations.

**Pull request merged**
