### PR TITLE
Impls of ToSql for different generic types (Box, Cow, Rc, Arc).

### PR DESCRIPTION
**Pull request by zero-systems**

### CODE REVIEW

**Comment by thomcc** [comment]
Probably worth adding FromSql too (and implementations for Arc<str> / Rc<str>), but that could be done later too.

**Comment by zero-systems** [comment]
I also see there is no implementation for `Path`. I think there must be another implementations for `Path` and different generic types like `Arc`, `Rc` (as `thomcc` wrote)), `Box`, `Cow`(there is only implementation for `Cow<'_, str>`)

**Comment by gwenn** [comment]
LGTM

**Comment by gwenn** [comment]
Thanks.

**Pull request merged**
