### PR TITLE
Add Helpful Note To Beginners

### PR DESCRIPTION
**Pull request by vthg2themax**
Add a helpful requirement note for beginners to get started using this library. Please let me know if you would like any additional help with this project, and if I can be of assistance with this request as well. Thank you!

### CODE REVIEW

**Comment by gwenn** [comment]
I am not sure it is the right suggestion.
A better one would be to use the `bundled` feature:
```toml
rusqlite = {version="0.17", features=["bundled"]}
```

**Comment by vthg2themax** [comment]
Where would you put that text? I thought the latest version of rusqlite in the Cargo.toml was:
[dependencies]
rusqlite = "0.9.5"

**Comment by gwenn** [comment]
https://crates.io/crates/rusqlite
> rusqlite = "0.17.0"
?

**Comment by vthg2themax** [comment]
Ha! The extension I have installed in VS Code shows the version numbers incorrectly.
However, the question I have still stands. Where should I put:
rusqlite = {version="0.17", features=["bundled"]}
Does it go in the Cargo.toml file?

**Comment by gwenn** [comment]
Yes.
See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#choosing-features and

**Comment by vthg2themax** [comment]
Awesome, thank you for your time! I removed the package and changed the Cargo dependency information to include the bundled part, and it worked as expected. Again, thank you for your helpful pointer!

**Comment by gwenn** [comment]
Do you mind closing this PR ?

**Pull request closed without merging**
