### PR TITLE
Update to latest version of SQLite3 3.24.0 #326

### PR DESCRIPTION
**Pull request by casret**
Shell script worked great!

### CODE REVIEW

**Comment by casret** [comment]
Looks like it's not working on linux or windows, was fine on my macos laptop.  Let me poke around.

**Comment by casret** [comment]
Oh, the bindgen generated are different.  What platform is the checked in one supposed to be?

**Comment by gwenn** [comment]
Thanks you for testing.
On linux (Linux archlinux.vagrant.vm 4.16.13-2-ARCH), upgrade works as expected:
https://travis-ci.org/gwenn/rusqlite/builds/403656798
https://ci.appveyor.com/project/gwenn/rusqlite/build/1.0.282
Maybe it is because i am using rust nightly (rustc 1.29.0-nightly (64f7de921 2018-07-12)) ?
I will keep you posted if I find exactly why it fails for you.

**Comment by casret** [comment]
Yeah, your branch works on my laptop and server as well.  I'll close this one.

**Comment by gwenn** [comment]
Ok,
I can reproduce the problem on MacOS.
https://travis-ci.org/gwenn/rusqlite/builds/403825217
https://ci.appveyor.com/project/gwenn/rusqlite/build/1.0.283

**Pull request closed without merging**
