### PR TITLE
Support for sqlite vtables as loadable extensions

### PR DESCRIPTION
**Pull request by jrandall**
Implements support to author sqlite loadable extensions (https://sqlite.org/loadext.html) using rusqlite, including the ability to write vtables in Rust and use them from other languages or the `sqlite3` CLI. 

The two main features that configure this are `loadable_extension` or `loadable_extension_embedded`. The first is used when a rust crate is a standalone loadable extension that itself implements an extension entrypoint (i.e. by implementing an `sqlite3_X_init` function ). The embedded version is intended if the rust crate implements functionality that is statically linked into a loadable extension. For example, a rust crate using `loadable_extension_embedded` could implement a vtable but not provide a loadable extension entrypoint itself, but rather expects to be embedded within a loadable extension.

The generated sqlite bindings are different when loaded as an extension or as an embedded extension (note that in C one would need to include `sqlite3ext.h` instead of `sqlite3.h`), so this change requires additional pre-built bindings to be created. Rather than generate them manually, we opted to write a script to generate them using sources downloaded from sqlite.org (see `libsqlite3-sys/bindgen-bindings/generate-bindgen-bindings.sh`). This PR includes prebuilt bindings for seven versions of sqlite for both the normal, extension, and embedded extension modes.

### CODE REVIEW

**Comment by jrandall** [comment]
I see that the travis CI checks are failing. This appears to be because the build script now requires `rustfmt` to format the bindings whereas previously they were being formatted by bindgen. The reason for this change is that the extension and embedded extension bindings rely on some code that are added to the bindgen-generated bindings by the build script. 

Can we add `rustfmt` to the travis CI build environment, and is this an acceptable build-time dependency to have?

**Comment by gwenn** [comment]
Why not update [rusqlite/libsqlite3-sys/upgrade.sh](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/upgrade.sh) ?

**Comment by jrandall** [comment]
> Why not update [rusqlite/libsqlite3-sys/upgrade.sh](https://github.com/jgallagher/rusqlite/blob/master/libsqlite3-sys/upgrade.sh) ?

Because I didn't realize it existed. I did look for documentation on how to generate the pre-built bindings but didn't find anything. I am happy to incorporate my changes into the existing script, though we may want to add some docs (or possibly change the name) to make it clear that it should be used to (re)generate the prebuilt bindgen bindings.

**Comment by gwenn** [comment]
Do you know if your PR fixes or is related to #524 ?

**Comment by jrandall** [comment]
Yes, this should implement a fix to #524 
I've been rather busy lately but will try to get to merging my changes into the existing `upgrade.sh` script as soon as I can.

**Comment by jrandall** [comment]
I have added some notes on how to use this functionality to implement a rust sqlite extension in #524: https://github.com/jgallagher/rusqlite/issues/524#issuecomment-507787350

**Comment by gwenn** [comment]
Many thanks.

**Comment by phiresky** [comment]
Could this get merged at some point? I'm trying to create a sqlite extension so this would be great.

**Comment by jrandall** [comment]
closing in favor of #631

**Pull request closed without merging**
