### PR TITLE
Add optional support for rust-url

### PR DESCRIPTION
**Pull request by thomcc**
As described on the tin.

P.S. It would be nice to get a release in the semi-near future.

### CODE REVIEW

**Comment by gwenn** [comment]
`FromSql`/`ToSql` for UDT can be implemented by dependent crates. 
So I am not sure we should add this to `rusqlite`.

**Comment by thomcc** [comment]
Users can't provide an implementation for this for Url, either this crate or the url crate has to. Given that the url crate isn't even willing to add the dep on serde (they provide a separate crate for serde support, which works but is a pain), it makes more sense to add it here.

Besides, `rust-url` is one of the most widely used crates on crates.io, and rusqlite already does this for `serde_json` and `chrono`.

**Comment by gwenn** [comment]
I checked on [this page](https://www.postgresql.org/docs/11/datatype.html) and saw nothing about `url` (but `json` and `date/time` types are).
And I guess you can't define an alias to `Url` and use it everywhere.
So fine, let merge this PR.

**Comment by gwenn** [comment]
@thomcc version 0.17 released with many breaking changes...

**Pull request merged**
