### PR TITLE
Fix error when building with `uuid` and `functions` features.

### PR DESCRIPTION
**Pull request by derekdreery**

### CODE REVIEW

**Comment by gwenn** [comment]
Would you mind updating the travis script ?
```diff
-  - cargo test --features "backup blob chrono csvtab functions hooks limits load_extension serde_json trace url vtab"
+  - cargo test --features "backup blob chrono csvtab functions hooks limits load_extension serde_json trace url uuid vtab"
```

**Comment by derekdreery** [comment]
Sure, but I'm not sure this patch is correct yet. Are the error types I'm converting to correct? I'm pretty sure they're not at present.

**Comment by derekdreery** [comment]
I think this is ready for review again. :)

**Comment by gwenn** [comment]
Thanks.

**Pull request merged**
