### PR TITLE
make bind_parameters() on Statement public

### PR DESCRIPTION
**Pull request by jrandall**
When implementing a vtable based on an underlying rusqlite connection, we have found it helpful in the `filter` implementation to be able to build a Statement by passing a Vec<Values> to bind_parameters() without actually executing the query (yet). We then convert the Statement into a RawStatement (see #636) and store that on the VTabCursor. Only if our `next` implementation is later called do we actuallt execute the query (by calling `step()` on the raw statement).

### CODE REVIEW

**Comment by thomcc** [comment]
Is there any reason you can see not to do this for bind_parameters_named too? If not, can you do that?

**Comment by thomcc** [comment]
I think we should do #668 instead. It's less ergonomic but allows use in more scenarios. It's also easier to document and seems less error prone.

**Comment by thomcc** [comment]
I'm going to close this since we landed #668. The ergonomics of that are rougher, but I think we'd accept a PR for additional functions with better ergonomics if you're still interested.

**Comment by jrandall** [comment]
Ok, after #668 it appears that we should be able to implement our own version of `bind_parameters` that uses the new `raw_bind_parameter` interface. I'm really not sure what the problem is with making `bind_parameters` public, though. 

The `execute` method and the `query` method are both public and pass the `params` argument it exposes directly through to `bind_parameters` so the interface for `bind_parameters` seems like it is already constrained by those public interfaces and nothing is being gained by keeping `bind_parameters` private. Am I missing something?

I did miss that `bind_parameters_named` even exists - I agree they should both be made public.

**Comment by thomcc** [comment]
The main reason I'm hesitant is that it doesn't seem that useful directly; that is, you couldn't implement the functionality in #668 given a stable bind_parameters, but the other way is true.

I also plan on changing this interface somewhat, since I find the duplication everywhere to be annoying (#609). I also consider the necessity of `NO_PARAMS` to be a bit of a design wart. I have ideas for how to fix this, but need to find the time (Perhaps next week I'll have more time?).

I would have done this for 0.23, but I was not really wanting to do a big API overhaul in that release since it had a number of security fixes.

**Comment by jrandall** [comment]
I agree that we *can* now implement our own bind_parameters using the new `raw_bind_parameter` interface from #668 -- that's great and it is good to have a lower level interface available in case we need it. 

However, I don't really see why we can't expose both a low-level interface and a higher level interface for this. I guess the reasoning is probably that you are planning to do away with the `_named` versions and so this will all be changing anyway -- in that case perhaps the replacement API for executing a statement with either named or positional params could include high-level public functions for binding parameters and executing the statement separately (in addition to a convenience function for doing the full execution in one go)?

**Comment by thomcc** [comment]
Yeah, that seems reasonable to me.

**Pull request closed without merging**
